In [ ]:
#f = 'ClubPerformance_with_FISCAL_cleaned.csv'
#f = 'TMI_ClubPerfandDivisionMerged_toNov2025.csv'
f = 'FindAClub.csv'
df_d95 = pd.read_csv(f, sep=',', dtype = str, encoding="utf-16") #använd typ alltid (om inte Excel export CSV)

In [15]:
import streamlit
import pandas as pd
from etl.sql_connection import sql_engine
from sqlalchemy import text
from datetime import datetime

In [16]:
engine = sql_engine()

In [17]:


#Parameteriserade queries

sql = text("""
SELECT *
FROM "FindAClub"
WHERE "District" = :district
""")

df_d95 = pd.read_sql(
    sql,
    engine,
    params={
        "district": "95"
    }
)

df_d95

,District,Area,Division,Club Number Original,Club Name,Charter Date:,Location,Address,City,State,...,Club-Website,Club-Email,Facebook,Longitude,Latitude,Advanced?,Prospective-Club?,Suspended date,Club numeric,Filename
0,95,02,F,CB-00009730,Famous Toastmasters Mainz,1994-01-01,"The Good Coffee Mainz, once per month<br>Once ...",Steingasse 24,Mainz,None,...,http://www.famous-toastmasters.org/,famoustoastmasters@gmail.com,https://www.facebook.com/FTMW,8.26719,50.00090,FALSE,FALSE,None,9730,FindAClubOldandNewMerged excel.xlsx
1,95,02,G,CB-00644226,Fabulastic Women In Toastmasters,2004-04-01,online,Druveforsvägen 8,Borås,None,...,None,alorenz@lorenzsoft.de,https://www.facebook.com/#!/groups/8782769246,12.93849,57.71559,FALSE,FALSE,None,644226,FindAClubOldandNewMerged excel.xlsx
2,95,03,F,CB-00962433,Rhetorik-Club Bergstraße e.V.,2007-06-18,Gaststätte Weiherhaus,Saarstraße 56,Bensheim,None,...,http://www.rhetorik-club-bergstrasse.de/,kontakt@rhetorik-club-bergstrasse.de,None,8.60830,49.68810,FALSE,FALSE,None,962433,FindAClubOldandNewMerged excel.xlsx
3,95,02,B,CB-03657516,Seafront Toastmasters,2015-05-08,"ARHK building, room 411<br>and online",Arendal Skans,Gothenburg,None,...,None,berndt.forssell@volvo.com,None,11.81924,57.69544,FALSE,FALSE,None,3657516,FindAClubOldandNewMerged excel.xlsx
4,95,02,B,CB-07217055,Ericsson Gothenburg Toastmasters,2019-05-01,Ericsson Lindholmen Gothenburg Sweden,Lindholmspiren 11,Gothenburg,None,...,https://tmclub.eu/view_meeting.php?c=1522,None,None,11.94092,57.70589,FALSE,FALSE,None,7217055,FindAClubOldandNewMerged excel.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,95,None,None,1563553,HanseRedner Rostock,2011-07-20,None,None,None,None,...,None,None,None,NaN,NaN,None,None,None,1563553,Appended George Marshall files for lookup.xlsx
204,95,None,None,1940745,Safer Toasters,2011-08-09,None,None,None,None,...,None,None,None,NaN,NaN,None,None,2013-06-30,1940745,Appended George Marshall files for lookup.xlsx
205,95,None,None,1971420,Braila Toastmasters,2013-08-22,None,None,None,None,...,None,None,None,NaN,NaN,None,None,None,1971420,Appended George Marshall files for lookup.xlsx
206,95,None,None,2909538,Toastmasters - Dr. Reddy's,2013-01-11,None,None,None,None,...,None,None,None,NaN,NaN,None,None,2013-09-30,2909538,Appended George Marshall files for lookup.xlsx
207,95,None,None,3372975,Toastmasters w Orange,2014-10-01,None,None,None,None,...,None,None,None,NaN,NaN,None,None,None,3372975,Appended George Marshall files for lookup.xlsx

In [18]:
df_d95.to_csv('FindAClub.csv', encoding="utf-16", index = False)

In [20]:
import streamlit as st
import pandas as pd
import numpy as np
import pydeck as pdk

st.write("Streamlit has lots of fans in the geo community. 🌍 It supports maps from PyDeck, Folium, Kepler.gl, and others.")

#chart_data = pd.DataFrame(
 #  np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
  # columns=['lat', 'lon'])

chart_data = df_d95

lon = "Longitude"
lat = "Latitude"


st.pydeck_chart(pdk.Deck(
    map_style=None,
    initial_view_state=pdk.ViewState(
        latitude=37.76,
        longitude=-122.4,
        zoom=11,
        pitch=50,
    ),
    layers=[
        pdk.Layer(
           'HexagonLayer',
           data=chart_data,
           get_position='[lon, lat]',
           radius=200,
           elevation_scale=4,
           elevation_range=[0, 1000],
           pickable=True,
           extruded=True,
        ),
        pdk.Layer(
            'ScatterplotLayer',
            data=chart_data,
            get_position='[lon, lat]',
            get_color='[200, 30, 0, 160]',
            get_radius=200,
        ),
    ],
))

2026-03-13 16:36:34.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-13 16:36:34.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-13 16:36:34.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-13 16:36:34.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

TypeError: vars() argument must have __dict__ attribute

In [13]:
chart_data = pd.DataFrame(
   np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
   columns=['lat', 'lon'])

In [14]:
chart_data

           lat         lon
0    37.792573 -122.386145
1    37.778423 -122.411758
2    37.740529 -122.396704
3    37.739291 -122.367183
4    37.751518 -122.410496
..         ...         ...
995  37.753932 -122.414420
996  37.770987 -122.405933
997  37.747052 -122.406327
998  37.767393 -122.419769
999  37.727555 -122.430236

[1000 rows x 2 columns]

In [7]:
np.random.randn(1000, 2)

array([[ 1.35127316, -0.11330115],
       [-0.8090239 ,  1.36238827],
       [ 0.0229675 , -1.42609305],
       ...,
       [ 0.03620454,  1.95320726],
       [ 0.75627476,  0.64898598],
       [ 1.03643637,  0.53218709]], shape=(1000, 2))